[project]
name = "banking-loss-distribution"
version = "0.1.0"
description = "Banking Sector Loss Distribution Model"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "streamlit-sortables>=0.3.1",
    "streamlit>=1.42.0",
]
